### ISSUE TITLE
Plugin dont work, infinite load

### ISSUE THREAD

**Issue by asturmas** [cloudflare/Cloudflare-CPanel#119] opened 2016-12-06 01:48 UTC
Hello,
We have installed the last version of plugin in two brand new cPanel servers and in both the plugin dont work and display a infinite loading..

![screenshot_1](https://cloud.githubusercontent.com/assets/12483819/20909840/e186335c-bb55-11e6-845a-22659a136623.png)

Domain tab show the domain in inactive state but button "Provision domain with CNAME setup" dont work. Any idea?

Thanks,

**Comment by jwineman** [comment] 2016-12-06 01:49
Hi @asturmas,

Are there any errors in the PHP error log or the browser's development console?  
What browser are you using?

Thanks,
John

**Comment by asturmas** [comment] 2016-12-06 01:56
Hello,
What error log, in account? No.
Firefox or Chrome have some problem in different computers.

![screenshot_2](https://cloud.githubusercontent.com/assets/12483819/20909994/c484d0c8-bb56-11e6-8752-8ae599727593.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/12483819/20910001/d2cb344c-bb56-11e6-97f1-e02f8487310a.png)

No errors when load the page only when click on button to provision.

**Comment by jwineman** [comment] 2016-12-06 03:32
I see the partial zone provisioning is erroring out, there should be errors in the cPanel error log at `/usr/local/cpanel/logs/error_log`.  If you tail it do what do you see?

**Comment by asturmas** [comment] 2016-12-07 09:40
Hello,
I dont see any errors in /usr/local/cpanel/logs/error_log :(

**Comment by jwineman** [comment] 2016-12-11 18:09
In the log I see `ZONE_PROVISION_CNAME_ERROR` which means it is erroring out.  There should be an error in the log.  If you click the "network" tab of the browser console you should see the AJAX request for the cname provisioning, can you post the response?

**Comment by bryyyon** [comment] 2016-12-24 00:45
I'm seeing a similar problem under cPanel 60.0.25. In my case, the browser console messages stop after `ZONE_SET_ACTIVE_ZONE`.  Nothing is logged to cPanel's error_log.  The latest version of the CloudFlare cPanel plug-in has been re-installed.

I've set `debug: true` in `/usr/local/cpanel/base/frontend/paper_lantern/cloudflare/config.js` and debug output is now present in error_log.  The debug information doesn't appear to yield anything to aid troubleshooting, sadly.  The debug information includes HTTP requests and responses to api.cloudflare.com and these appear to complete successfully.  The plug-in's XHR request to proxy.live.php appears to return the api.cloudflare.com response JSON. I've included that below. (Note: The name field value has been changed to example.com for privacy.)

`{"result":[{"name":"example.com","plan":{"name":""},"type":"","status":"inactive"}],"success":true}`

Any advice is appreciated!

**Comment by panayotb** [comment] 2016-12-24 04:44
By the way, how do you reinstall the plugin? Because I had an issue that was not fixed by running 
`/usr/local/cpanel/bin/cloudflare_update.sh force`

I needed to:

`rm -r /usr/local/cpanel/3rdparty/php/54/lib/php/cloudflare `

edit cloudflare_update.sh to replace 
`FORCE_INSTALL=false`
with
`FORCE_INSTALL=true`

run
`/usr/local/cpanel/bin/cloudflare_update.sh`

Then replace it back with 
`FORCE_INSTALL=false`

**Comment by bettinz** [comment] 2017-01-02 23:42
Same problem here

**Comment by jwineman** [comment] 2017-01-03 18:51
Hi Guys,

Thanks for reporting this!  I think we know the root cause and are working on a fix.  I'll update this thread when its been released.

Thanks,
John

**Comment by asturmas** [comment] 2017-01-03 21:47
Good news John, we will wait for the update.

Thanks!

**Comment by georgeappiah** [comment] 2017-01-08 09:07
Still waiting for the promised update. Right now CloudFlare is broken on all my cPanel servers, new and old (old servers broke after upgrade).

**Comment by asturmas** [comment] 2017-01-08 23:11
Same here, CloudFlare still dont work in a lot of cPanel servers and received every day a lot of customer complaints about this.
Any ETA @jwineman ?

**Comment by djprmf** [comment] 2017-01-08 23:54
I also have notice this problem in 3 different servers, only in new domains.
Already active domains work fine, no errrors in the logs (as reported before)...
Any workaround or update being done?

**Comment by jwineman** [comment] 2017-01-09 18:46
Hi All,

Targeting a release to fix this by end of next week.  Reverting to 6.0.9 should be a suitable workaround until then.

Thanks,
John

**Comment by loweryaustin** [comment] 2017-01-18 16:38
I'm also seeing this on my cPanel server.
cPanel: 11.62.0.4
Cloudflare Plugin: 6.1.1

**Comment by cenourinha** [comment] 2017-01-24 19:11
We're still waiting for a new release that fix this bug. :\

**Comment by jwineman** [comment] 2017-01-24 19:15
Hi,

The following issues were fixed in [this PR](https://github.com/cloudflare/cloudflare-plugin-frontend/pull/79):

- cPanel will now default to the domain page on page load
- Loading spinner doesn't spin forever on unprovisioned domains.
- Errors are correctly propagated back to the front end now.

I'm fixing some style issues as we speak and then I'll be ready to release.

Thanks,
John

**Comment by loweryaustin** [comment] 2017-01-30 08:54
Is there a place to keep track of the release @jwineman ?

**Comment by thellimist** [comment] 2017-01-30 12:04
@loweryaustin https://github.com/cloudflare/Cloudflare-CPanel/releases

**Comment by jwineman** [comment] 2017-01-31 18:08
Hi Guys,

This has been fixed in [6.1.2](https://github.com/cloudflare/Cloudflare-CPanel/releases/tag/v6.1.2).  Sorry about the delay - all of our plugins use the same [frontend](https://github.com/cloudflare/cloudflare-plugin-frontend/) and it had changed a lot since the last time cPanel was updated so there was significant rework involved in getting it ready to release after the bug was fixed.

Thanks,
John

**Closed by jwineman** 2017-01-31 18:08 UTC
