### ISSUE TITLE
DNS Records don't sync with Full DNS type

### ISSUE THREAD

**Issue by andrekutianski** [cloudflare/Cloudflare-CPanel#156] opened 2017-07-21 03:43 UTC
On CloudFlare cPanel plugin version 7.0.0 on WHM 64.0 (build 33) the DNS records don't sync with CloudFlare full DNS Zone. After remove or add sub-domains or try to point some existing domain, the DNS records like CNAME, A and MX do not sync. Wen try to add a new domain with full zone, the same happens.

CloudFlare Plugin: 7.0.0
WHM: 64.0.33
SO: CloudLinux 6.9 x86_64

**Comment by jwineman** [comment] 2017-07-21 19:05
Hi,

Thanks for reporting this!  I haven't investigated yet but I assume the Host API `full_zone_set` call isn't importing DNS records the same way the v4 API full zone set call does.  The work around for now is to orange cloud the DNS records from the cPanel plugin UI but I've also created a ticket to track this and we'll start working on a fix!

Tracking internally PI-1216

Thanks,
John

**Comment by andrekutianski** [comment] 2017-07-21 19:08
Thanks @jwineman, If there is any other information I can provide to debug the problem, please ask me

**Comment by jwineman** [comment] 2017-07-21 19:18
I think we have what we need, thanks!  I'm able to reproduce I just haven't determined the root cause yet.

**Comment by garrettgalow** [comment] 2017-08-23 18:37
@andrekutianski can you give this another try and let me know if it is fixed? We pushed an update yesterday that should fix this. The bug was on the backend, so there wasn't a change to this repo's code.

**Comment by andrekutianski** [comment] 2017-08-25 23:21
@garrettgalow In the tests I performed the DNS updates again

**Comment by manatarms** [comment] 2017-08-28 18:42
@andrekutianski Closing since confirmed resolved. Thanks for the assist.

**Closed by manatarms** 2017-08-28 18:42 UTC

**Comment by thellimist** [comment] 2017-10-09 16:49
Internal code for the fxi PI-1216

**Comment by efelinto** [comment] 2017-11-14 20:37
Hello,
I have the same problem. I created an A record in cPanel and the change was not added to my Cloudflare account that is using Full DNS in cPanel.
Is there a cron that I price configure or something more for this change to be done in an instant?

**Comment by imorandinwnp** [comment] 2021-03-12 18:13
Same here
